%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\email_000\Documents\MATLAB\LV Plot List.xlsx
%    Worksheet: Sheet1
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2018/03/08 03:01:02

%% Import the data
[~, ~, raw] = xlsread('C:\Users\email_000\Documents\MATLAB\LV Plot List.xlsx','Sheet1');
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};

%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Create table
LVPlotList = table;

%% Allocate imported array to column variable names
LVPlotList.VarName1 = data(:,1);
LVPlotList.VarName2 = data(:,2);
LVPlotList.VarName3 = data(:,3);
LVPlotList.VarName4 = data(:,4);
LVPlotList.VarName5 = data(:,5);
LVPlotList.VarName6 = data(:,6);

%% Clear temporary variables
clearvars data raw R;